# Generated by Django 5.1.7 on 2025-05-21 16:10

import django.db.models.deletion
import loja.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icon', models.FileField(blank=True, default=None, null=True, upload_to='uploads/categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagens_de_Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('telemovel', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=loja.models.user_directory_path)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, choices=[('aveiro', 'Aveiro'), ('beja', 'Beja'), ('braga', 'Braga'), ('braganca', 'Bragança'), ('castelo_branco', 'Castelo Branco'), ('coimbra', 'Coimbra'), ('evora', 'Évora'), ('faro', 'Faro'), ('guarda', 'Guarda'), ('leiria', 'Leiria'), ('lisboa', 'Lisboa'), ('portalegre', 'Portalegre'), ('porto', 'Porto'), ('santarem', 'Santarém'), ('setubal', 'Setúbal'), ('viana_do_castelo', 'Viana do Castelo'), ('vila_real', 'Vila Real'), ('viseu', 'Viseu')], max_length=255, null=True)),
                ('cp', models.CharField(blank=True, max_length=20, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venda', models.CharField(choices=[('venda', 'Venda Direta'), ('leilao', 'Leilão')], default='venda', max_length=10)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('inicio_leilao', models.DateTimeField(blank=True, null=True)),
                ('fim_leilao', models.DateTimeField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, choices=[('aveiro', 'Aveiro'), ('beja', 'Beja'), ('braga', 'Braga'), ('braganca', 'Bragança'), ('castelo_branco', 'Castelo Branco'), ('coimbra', 'Coimbra'), ('evora', 'Évora'), ('faro', 'Faro'), ('guarda', 'Guarda'), ('leiria', 'Leiria'), ('lisboa', 'Lisboa'), ('portalegre', 'Portalegre'), ('porto', 'Porto'), ('santarem', 'Santarém'), ('setubal', 'Setúbal'), ('viana_do_castelo', 'Viana do Castelo'), ('vila_real', 'Vila Real'), ('viseu', 'Viseu')], max_length=255, null=True)),
                ('estado', models.CharField(choices=[('1', 'Mau'), ('2', 'Muito Usado'), ('3', 'Usado'), ('4', 'Ligeiramente Usado'), ('5', 'Como novo')], default='3', max_length=10)),
                ('nome', models.CharField(max_length=60)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loja.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('licitado_a', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitacoes', to='loja.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loja.product')),
            ],
        ),
    ]
