# Generated by Django 5.1.6 on 2025-02-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_contactmessage_mensagens_de_contactos'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/categorias/'),
        ),
    ]
