# Generated by Django 5.1.6 on 2025-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_categoria_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/categorias/'),
        ),
    ]
