# Generated by Django 5.1.6 on 2025-02-20 17:02

import loja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_product_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=loja.models.product_image_upload_path),
        ),
    ]
