# Generated by Django 5.1.6 on 2025-02-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='uploads/products/'),
        ),
    ]
