# Generated by Django 5.1.6 on 2025-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estado',
            field=models.CharField(choices=[('novo', 'Como novo'), ('bom', 'Bom'), ('mau', 'Mau')], default='bom', max_length=10),
        ),
    ]
