# Generated by Django 5.1.6 on 2025-03-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_product_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profiles/'),
        ),
    ]
