# Generated by Django 5.1.6 on 2025-03-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_user_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
    ]
