# Generated by Django 5.1.6 on 2025-03-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_remove_user_has_module_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='localidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
