# Generated by Django 5.1.7 on 2025-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_alter_user_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telemovel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
