# Generated by Django 5.1.7 on 2025-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_alter_user_telemovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='estado',
            field=models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='3', max_length=10),
        ),
    ]
