# Generated by Django 5.1.7 on 2025-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_alter_product_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo_venda',
            field=models.CharField(choices=[('venda', 'Venda Direta'), ('leilao', 'Leilão')], default='venda', max_length=10),
        ),
    ]
