# Generated by Django 5.1.7 on 2025-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_product_tipo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fim_leilao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inicio_leilao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
