# Generated by Django 5.1.7 on 2025-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_product_fim_leilao_product_inicio_leilao'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='localidade',
            field=models.CharField(blank=True, choices=[('aveiro', 'Aveiro'), ('beja', 'Beja'), ('braga', 'Braga'), ('braganca', 'Bragança'), ('castelo_branco', 'Castelo Branco'), ('coimbra', 'Coimbra'), ('evora', 'Évora'), ('faro', 'Faro'), ('guarda', 'Guarda'), ('leiria', 'Leiria'), ('lisboa', 'Lisboa'), ('portalegre', 'Portalegre'), ('porto', 'Porto'), ('santarem', 'Santarém'), ('setubal', 'Setúbal'), ('viana_do_castelo', 'Viana do Castelo'), ('vila_real', 'Vila Real'), ('viseu', 'Viseu')], max_length=255, null=True),
        ),
    ]
