# Generated by Django 5.1.7 on 2025-04-23 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0025_product_localidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
