# Generated by Django 5.1.7 on 2025-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='estado',
            field=models.CharField(choices=[('1', 'Mau'), ('2', 'Muito Usado'), ('3', 'Usado'), ('4', 'Ligeiramente Usado'), ('5', 'Como novo')], default='3', max_length=10),
        ),
    ]
