# Generated by Django 5.1.7 on 2025-04-22 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_user1_alter_conversation_user2_and_more'),
        ('loja', '0025_product_localidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='loja.product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user1', 'user2', 'product')},
        ),
    ]
